document.getElementById("bookname").innerHTML = "Silmarillion";
document.getElementById("chapter").innerHTML = "Death of Turin";
document.getElementById("writing").innerHTML = "'Hail Gurthang! No lord or loyalty dost thou know, save the hand that wieldeth thee. From no blood with thou shrink. Wilt thou therefore take Turin Turambar, wilt thou slay me swiftly?' And from the blade rang a cold voice in answer: 'Yea, I will drink thy blood gladly, that so I may forget the blood of Beleg my master, and the blood of Brandir slain unjustly. I will slay thee swiftly.'";
//Placeholders from my favorite passage until I get this thing running properly


//FAULTY CODE
//document.getElementsByClassName("snip1").innerHTML = <hx>"Death of Turin"</hx>
//document.getElementsByClassName("snip2").innerHTML = <hx>Oath of Feanor</hx>;
/*document.getElementsByClassName("snip3").innerHTML = <hx>Oath of Feanor in Quenya</hx>;
document.getElementsByClassName("snip4").innerHTML = <hx>Morgoth's promise to Hurin</hx>;
document.getElementsByClassName("snip5").innerHTML = <hx>Duel of Thu and Finrod</hx>;
document.getElementsByClassName("snip6").innerHTML = <hx>Of Beren</hx>;
document.getElementsByClassName("snip7").innerHTML = <hx>Gorlim's betrayal</hx>;
document.getElementsByClassName("snip8").innerHTML = <hx>House of Ransom</hx>;
document.getElementsByClassName("snip9").innerHTML = <hx>Death of Glaurung</hx>;
document.getElementsByClassName("snip10").innerHTML = <hx>Greeting to Earendil</hx>;


/*to add:
-conditional statements that will track each book selected
-snippets that change depending on the book selected
-buttons that change text box contents

Possibly in future:
-text file that would have all the texts in it, and each button would
call the contents of a certain line*/