var book = "null", snippet = "null";

    document.getElementById("bookname").innerHTML = "Welcome to the Tolkien Library";
    document.getElementById("chapter").innerHTML = "";
    document.getElementById("writing").innerHTML = "This is a space to share unreleased or hard to come by snippets from the works of JRR Tolkien";
   // document.getElementsByClassName("snip1").innerHTML = <hx>"Test to replace snip1"</hx>

    function readHobbit(){
    document.getElementById("bookname").innerHTML = "Hobbit";
    document.getElementById("chapter").innerHTML = "";
    document.getElementById("writing").innerHTML = "Choose snippet from the Hobbit";
    book = "Hobbit";
}
function readLOTR(){
    document.getElementById("bookname").innerHTML = "The Lord of the Rings";
    document.getElementById("chapter").innerHTML = "";
    document.getElementById("writing").innerHTML = "Choose snippet from the Lord of the Rings";
    book = "LOTR";
}
function readSilm(){
    document.getElementById("bookname").innerHTML = "The Silmarillion";
    document.getElementById("chapter").innerHTML = "";
    document.getElementById("writing").innerHTML = "Choose snippet from the Silmarillion";
    book = "Silmarillion";
}
function readUFT(){
    document.getElementById("bookname").innerHTML = "The Unfinished Tales";
    document.getElementById("chapter").innerHTML = "";
    document.getElementById("writing").innerHTML = "Choose snippet from the Unfinished Tales";
    book = "UnfinishedTales";
}
function readHOME(){
    document.getElementById("bookname").innerHTML = "History of Middle-Earth";
    document.getElementById("chapter").innerHTML = "";
    document.getElementById("writing").innerHTML = "Choose snippet from the History of Middle Earth";
    book = "HOME";
}
function doSnip1(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Oath of Feanor";
        document.getElementById("writing").innerHTML = "Be he Foe or Friend\nFoul or Clean\nBrood of Morgoth or bright Vala";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {

    }
}
function doSnip2(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Oath of Feanor in Quenya";
        document.getElementById("writing").innerHTML = "Nai kotumo ar nilmo\nKalima Vala\nThauza ar poika Moringothonna";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip3(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Death of Fingolfin";
        document.getElementById("writing").innerHTML = "Then Morgoth hurled aloft Grond, the Hammer of the Underworld, and swung it down like a bolt of thunder. But Fingolfin sprang aside, and Grond rent a mighty pit in the earth... Many times Morgoth essayed to smite him, and each time Fingolfin leaped away, as a lightning shoots from under a dark cloud.";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip4(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Of Beren";
        document.getElementById("writing").innerHTML = "Text about Beren here";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip5(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Capture of Hurin";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip6(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Death of Glaurung";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip7(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Death of Turin Turambar";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip8(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "The last Feanorians";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip9(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        document.getElementById("chapter").innerHTML = "Hails to Earendil";
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}
function doSnip10(){
    if (book == "Hobbit") {

    } else if (book == "LOTR") {

    } else if (book == "Silmarillion") {
        
    } else if (book == "UnfinishedTales") {

    } else if (book == "HOME") {
        
    }
}